# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('equipe', models.CharField(max_length=50)),
                ('presente', models.CharField(choices=[('Sim', 'sim'), ('Não', 'não')], max_length=3)),
                ('quentinha', models.CharField(choices=[('Sim', 'sim'), ('Não', 'não')], max_length=3)),
            ],
        ),
    ]
